// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const texts = {
  splash_mint_title: 'Avatizer NFT - Free Mint',
  splash_mint_title_ugfs_1: 'MINT COMING SOON',
  splash_mint_title_ugfs_2: 'Free mint',
  splash_mint_title_ugfs_stop:'Sold out',
  splash_mint_description_ugfs_stop:'Find Ugly Faces NFTs on OpenSea',
  splash_mint_description_1: 'Whitelist only. One NFT per wallet.',
  splash_mint_description_2:
    'Allowlist and whitelist only. One NFT per wallet.',
  splash_mint_description_ugfs_1: 'You can check whether your wallet is on the Whitelist',
  splash_mint_description_ugfs_2: 'Only Whitelisters can mint Ugly Faces NFTs.',
  your_wallet_id: 'Your wallet ID',
  status_text_success: 'You are on the whitelist, minting will open soon',
  status_text_success_ugfs:'Whitelisting confirmed!',
  status_text_success_ugfs_1:'Mint starts at:',
  disconnect: 'Disconnect',
  switch_network: 'Switch network',
  status_switch_error: 'Network switch failed, try again',
  mint_now: 'Mint my Avatizer now',
  mint_now_ugfs:'MINT NFT',
  mint_now_ugfs_2:'MINT 2 NFTs',
  mint_now_ugfs_3:'MINT 3 NFTs',
  status_mint_success: 'Congrats! Your Avatizer has been minted',
  status_mint_success_ugfs: 'Congrats! Your Ugly Faces NFT has been minted',
  status_address_missing_in_whitelist:
    'Your wallet is not on the whitelist, minting not possible',
  status_address_missing_in_whitelist_ugfs:'Your wallet is not included on the Whitelist. Mint is not available.',
  manage_nft: 'Manage my Avatizers',
  status_getting_nft: 'Receiving NFT',
  status_getting_nft_ugfs:'Getting Ugly Faces NFT(s)',
  status_already_minted_nft: "You've minted your Avatizer already.",
  status_no_longer_ugfs:'Wallet can no longer receive NFTs',
  wallet_status_change_network: 'Please change network to Etherium',
  wallet_status_change_network_ugfs:'Please, switch the network to Ethereum',
  status_minted_sold_out: 'SOLD OUT',
  copyright_adsres: '1800 Diagonal Road #600, Alexandria, VA 22314, USA',
  copyright_company: '© Electronic Team, Inc.',
  status_minted_not_started: 'You are a bit early, minting will start soon.',
  connect_wallet: 'Connect my wallet',
  connect_wallet_ugfs: 'CONNECT WALLET',
  splash_mint_title_mng: 'Avatizer NFT - Free Mint',
  minting_ethereum_only: 'Minting on Ethereum only',
  generation: 'Daily reload',
  metamask_install: 'Install MetaMask',
  metamask_required: 'MetaMask wallet required',
  menu_text_mint: 'Free Mint',
  menu_text_manage: 'Manage my Avatizers',
  generate_active_note:
    "Every Avatizer is visually reloaded/updated daily at 5 pm UTC. Please note, once the new Avatizer is generated, the old one cannot be restored. You can pause daily reload for each Avatizer you own to keep the ones you like.<br><br><b class='modal-desc--note'>Note:</b> pausing or restoring daily reloads will incur gas fees. That's the way the blockchain works.",
  generate_paused_note:
    "This Avatizer will not update itself. Its current art will remain unchanged until you enable Daily Reloads.<br><br><b class='modal-desc--note'>Note:</b> pausing or restoring daily reloads will incur gas fees. That's the way the blockchain works.",
  generate_active_note_ugfs:"Every Ugly Faces NFT is visually reloaded/updated daily at 5 pm UTC. Please note, once the new look of an Ugly Faces NFT is generated, the old one cannot be restored. You can pause daily reloads for each Ugly Faces NFT you own to keep the ones you like.<br><br><b class='modal-desc--note'>Note:</b> pausing or restoring daily reloads will incur gas fees. That's the way the blockchain works.",
  generate_paused_note_ugfs:"This Ugly Faces NFT will not update itself. Its current art will remain unchanged until you enable Daily Reloads.<br><br><b class='modal-desc--note'>Note:</b> pausing or restoring daily reloads will incur gas fees. That's the way the blockchain works.",
  minting_soon: 'Avatizer Minting Soon',
  minting_stoped: 'Avatizer Minting is stoped',
  opensea_btn_text: 'Visit OpenSea',
  not_found_title: 'Ooops! Page Not Found.',
  not_found_description:
    'This page doesn’t exist or was removed! Don’t worry, you will be redirected to our homepage within',
  not_found_seconds: 'seconds',
  not_found_btn_text: 'Back to Home',
  status_on_whitelist_success: 'You are on the whitelist',
  status_nft_is_available: 'Your Avatizer NFT is available',
  status_nft_is_available_ugfs:' NFTs are available. Only gas payments are required.',
  status_nft_is_available_ugfs_1: 'NFT is available. Only gas payment required.',
  tokens_loading_start    :'Loading... one moment, please',
  tokens_loading_stop    :'You own %length% Avatizer(s)',
  tokens_loading_stop_ugfs    :'You own %length% Ugly Faces NFT(s)',
  tokens_loading_stop_quadart    :'You own %length% QuadArto NFTs',
	manage_nft_description: 'You can manage NFTs here from both collections',
	menu_text_manage_uglyfaces :'Manage Ugly Faces',
	menu_text_mint_uglyfaces : 'MINT Ugly Faces',
	menu_text_uglyfaces : 'Ugly Faces',
  manage_nft_ugfs_manage:'Manage my',
  manage_nft_ugfs:'Ugly Faces NFT(s)',
  status_mint_error:'Mint failed! Please try again!',
  status_mint_error_2:'Transaction canceled! Please try again!',
  quadarto_title: 'QuadArto',
  quadarto_tab_canvas: 'Canvas',
  quadarto_tab_managment: 'Management',
  quadarto_connect_btn: 'Connect Wallet',
  quadarto_notice_canvas: 'QuadArto canvas will be revealed on',
  quadarto_notice_top_canvas: 'QuadArto is an experimental cooperative pixel art project with a ',
  quadarto_notice_top_canvas_ancor: 'unique concept',
  quadarto_notice_canvas_reveal: 'This canvas depicts all 225 QuadArto NFTs and shows on the Initial QuadArto Token',
  quadarto_notice_connect: 'To view your QuadArto NFTs, please',
  quadarto_notice_switch_network: 'to the Ethereum network',
  quadarto_notice_missing_nfts: 'You have 0 QuadArto NFTs',
  quadarto_change_image : 'Upload your image',
  quadarto_draw_image : 'Drag and drop',
  quadarto_draw_image_1 : 'or browse for an image',
  quadarto_draw_image_2 : 'to generate pixel art',
  quadarto_image_format : 'JPG, JPEG, or PNG (max 5 MB)',
  quadarto_pixel_create_image : 'Creating Pixel Art',
  quadarto_loading_start: 'One moment, please. Loading <span class="loading-dots"></span>',
  quadarto_modal_description: 'Your image will appear on the canvas in a while. You can upload new images anytime you want, no need to pay gas fees.',
  quadarto_managment_text: 'Here you can upload new images to your QuadArto NFTs. Connect your wallet, click your token’s number, choose an image file, and wait until pixel art is created - that’s all. No need to pay gas fees, so you can upload unlimited times! The more tokens you own - the bigger images you create!',
  quadarto_canvas_text: 'Only 225 QuadArto NFTs combined represent the collection’s art on the Initial QuadArto Token and the canvas above. Holders can upload any image they want to their tokens, changing the canvas in real-time without transaction fees',
  quadarto_canvas_text_2: 'Also, no creator’s fee for pure art on OpenSea!'
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
